# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedrecommendation',
            unique_together=set([('user', 'feed')]),
        ),
    ]
