# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_charge', models.DateTimeField(blank=True, default=None, null=True)),
                ('stripe_customer_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PineUser',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='premiumuserdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
