# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
