# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160118_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
