# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160121_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cloud',
            field=models.URLField(blank=True, null=True, verbose_name='Cloud URL'),
        ),
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
