# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_default',
        ),
        migrations.AddField(
            model_name='site',
            name='default_feed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_site', to='feeds.Feed'),
        ),
    ]
