# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cloud',
            field=models.URLField(blank=True, null=True, verbose_name='Cloud URL'),
        ),
    ]
