# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20160122_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cached_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
