# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20170903_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.IntegerField(choices=[(0, 'Blog'), (1, 'Microblog')], default=0),
        ),
    ]
