# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20160119_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='word',
        ),
    ]
