# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_feed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(related_name='feeds', to='feeds.Tag'),
        ),
    ]
