# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('microblog', 'Microblog')], default='blog', max_length=10),
        ),
    ]
