# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20160122_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
