# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20160120_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='tags',
            new_name='tags',
        ),
    ]
