# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0006_auto_20170811_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_sites', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='sites', to='feeds.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.AddField(
            model_name='feed',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeds.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('site', 'rss_url')]),
        ),
    ]
