# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import feeds.models

def create_sites_from_feed(apps, schema_editor):
    """ For every feed in the system, create a related site object and poulate
    it, then set the relation between the site and the feed.
    """
    existing_feeds = feeds.models.Feed.objects.all()
    for feed in existing_feeds:
        site = feeds.models.Site(link=feed.link)
        site.save()
        feed.site = site
        feed.save()


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20170816_2304'),
    ]

    operations = [
        migrations.RunPython(
            create_sites_from_feed
        ),
        migrations.AlterField(
            model_name='feed',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeds.Site'),
        ),
    ]
