# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20170816_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.URLField(unique=True, verbose_name='Feed URL'),
        ),
    ]
