# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20160122_0543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([]),
        ),
    ]
