# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20170816_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
