# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-21 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20170816_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
