# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-22 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_auto_20170822_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='error',
        ),
    ]
